version: "v2.36.0-desktop.1"
services:
  api:
    build: ./api
    container_name: api
    ports:
      - '3001:3000'
    volumes:
      - ./api:/app
      - /app/node_modules
  ui:
    build: ./my-app
    container_name: react-my-app
    ports:
      - '3000:3000'
    volumes:
      - ./my-app:/app
      - /app/node_modules
    stdin_open: true
    tty: true
